
#### Scripts
##### SearchIncidentsV2
- Updated the Docker image to: *demisto/python3:3.10.1.27636*.
- Fixed an issue where multiple *id* values caused failure.
